export function renderCV(cv, { escape, icon, themeToggle }) {
  const socialLink = (symbol, href, text) => `<a class="cv-social-link" href="${escape(href)}">${icon(symbol)}<span>${escape(text)}</span></a>`;
  const sectionContent = cv.sections.map(section => {
    const entries = section.entries.map(entry => `<div class="cv-left-date">${escape(entry.date).replaceAll(' - ', ' — ')}</div><div${section.id === 'honors-and-awards' ? '' : ' class="cv-primary"'}>${escape(entry.primary)}</div>${entry.secondary ? `<div${section.id === 'teaching' ? ' class="cv-position"' : ''}>${escape(entry.secondary)}</div>` : ''}${entry.position ? `<div class="cv-position">${escape(entry.position)}</div>` : ''}${entry.description.length ? `<div class="cv-description">${entry.description.map(text => `<p>${escape(text)}</p>`).join('')}</div>` : ''}<div class="cv-spacer" aria-hidden="true"></div>`).join('');
    const skills = (section.skills || []).map(item => `<p class="cv-skill"><strong>${escape(item.category)}:</strong> ${escape(item.skills)}</p>`).join('');
    return `<h2 id="${section.id}">${escape(section.title)}</h2>${entries}${skills}${!entries && !skills ? '<div class="cv-empty" aria-hidden="true"></div>' : ''}`;
  }).join('');
  const intro = escape(cv.intro).replace('machine learning', '<strong class="cv-ai">machine learning</strong>').replace('platform engineering', '<strong class="cv-systems">platform engineering</strong>').replace('technical program management', '<strong class="cv-management">technical program management</strong>');
  return `<main class="cv" id="main"><div class="cv-heading"><h1 id="cv-title"><a href="/">${escape(cv.name)}</a></h1>${themeToggle()}</div><p id="cv-subtitle">${escape(cv.subtitle)}</p><div class="cv-intro">${intro}</div><div class="cv-image-links-wrapper"><div class="cv-image-links">${socialLink('home', '/', 'jordanbailey.dev')}${socialLink('mail', `mailto:${cv.email}`, cv.email)}${socialLink('pdf', '/cv.pdf', 'CV PDF')}</div><div class="cv-image-links">${socialLink('github', cv.github, '@jordanbailey00')}${socialLink('linkedin', cv.linkedin, 'jordanbaileypm')}<div class="cv-social-link" aria-hidden="true"></div></div></div><hr>${sectionContent}</main>`;
}
